config/routes.rb
Rails.application.routes.draw do
    
    get 'home/index'

    get 'home/login'

    root 'home#index'

    resources :workers

    jsonapi_resources :contacts

end

app/models/worker.rb
class Worker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @hello = "welcome to the ruby on rails world."
      
      session[:username] = "loki"
  end

  def login
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
      @worker = Worker.find(params[:id])
  end

  # GET /workers/new
  def new
      @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
      @worker = Worker.new(name:params[:name])

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(name:params[:name])
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.fetch(:worker, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/home/index.html.erb
<%= @hello %> <%= session[:username] %>


<%Worker.columns.map { |col|%>
    <br><br/>worker entity columns <b><%=col.name%></b>
<%}%>

app/views/home/login.html.erb
<h1>Home#login</h1>
<p>Find me in app/views/home/login.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Category</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/workers/_form.html.erb
<%= form_for(@worker) do |f| %>
  <% if @worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% @worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
name:<%= text_field_tag :name %><br/><br/>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form' %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Workers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%=worker.name%>&nbsp;</td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path %>

<br/>
<hr/>
<% 5.times do |i|%>
<%= i %> times to output the result.<br/>
<% end %>

<hr/>
<h3>Session</h3>
<%= debug session %>
<h3>Params</h3>
<%= debug params %>
<h3>Request</h3>
<%= debug request %>
<h3>Response</h3>
<%= debug response %>
<h3>headers</h3>
<%= debug headers %>
<h3>flash</h3>
<%= debug flash %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form' %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= @worker.name %></p>

<%= link_to 'Edit', edit_worker_path(@worker) %> |
<%= link_to 'Back', workers_path %>